import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import peopleJson from '../../libs/people-data';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';

export default function People() {
  const router = useRouter();

  const handleOnClick = (guid) => {
    router.push(`/people/${guid}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>People</h1>

        <div>
          {peopleJson.map(({ guid, name }) => {
            return (
              <li key={guid} onClick={() => handleOnClick(guid)}>
                {name}
              </li>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤</p>
      </footer>
    </div>
  );
}
