import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useSession, signIn, signOut } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();
  console.log(session);
  if (session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>
          <h2>Welcome to this Nextjs Auth page</h2>
          <h1>Hello {session?.user?.name}</h1>
          <img
            src={session?.user?.image}
            alt=''
            style={{ width: '100px', height: '100px', borderRadius: '50%' }}
          ></img>
          <p>You can only see this content when you are logged in</p>
          <br />
          <br />
          <button className={styles.signOutBtn} onClick={() => signOut()}>
            Sign Out
          </button>
        </main>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h2>Welcome to this Nextjs Auth page</h2>
        <p>You need to sign in to see content</p>
        <br />
        <button className={styles.signOutBtn} onClick={() => signIn()}>
          Sign In
        </button>
        <br />
      </main>
    </div>
  );
}
